[project]
name = "odoo-addons-oca-sign"
version = "17.0.20241203.0"
dependencies = [
    "odoo-addon-sign_oca>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
